# ============================================================================
# VARIABLES FOR AWS ORGANIZATIONS MODULE
# ============================================================================
#
# This file defines the input variables for the AWS Organizations module.
# These variables control the organization structure, naming, and configuration.
# All variables have sensible defaults but should be customized for your
# specific organizational requirements.

# ============================================================================
# ORGANIZATION CONFIGURATION
# ============================================================================

variable "organization_name" {
  description = <<-EOT
    Human-readable name for the AWS Organization.

    This name is used for:
    - Tagging organizational resources
    - Documentation and identification purposes
    - Internal reference and management

    Note: This is different from the organization ID which is automatically
    generated by AWS. Choose a name that clearly identifies your organization.
  EOT
  type        = string
  default     = "my-organization"

  validation {
    condition     = length(var.organization_name) > 0 && length(var.organization_name) <= 50
    error_message = "Organization name must be between 1 and 50 characters."
  }
}

# ============================================================================
# ORGANIZATIONAL UNIT CONFIGURATION
# ============================================================================

variable "stage_ou_name" {
  description = <<-EOT
    Name for the Stage Organizational Unit.

    This OU contains accounts for development, testing, and staging workloads.
    The name should be descriptive and follow your organization's naming convention.

    Examples: "Stage", "Development", "Non-Production", "Dev-Test"
  EOT
  type        = string
  default     = "Stage"

  validation {
    condition     = length(var.stage_ou_name) > 0 && length(var.stage_ou_name) <= 68
    error_message = "Stage OU name must be between 1 and 68 characters."
  }
}

variable "production_ou_name" {
  description = <<-EOT
    Name for the Production Organizational Unit.

    This OU contains accounts for live production workloads.
    The name should be descriptive and follow your organization's naming convention.

    Examples: "Production", "Prod", "Live", "Production-Workloads"
  EOT
  type        = string
  default     = "Production"

  validation {
    condition     = length(var.production_ou_name) > 0 && length(var.production_ou_name) <= 68
    error_message = "Production OU name must be between 1 and 68 characters."
  }
}
